export const trendingMovies = [
  {
    backgroundImg: "img/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
  },
  {
    backgroundImg: "img/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
  },
  {
    backgroundImg: "img/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
  },
  {
    backgroundImg: "img/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
  },
  {
    backgroundImg: "img/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
  },
  {
    backgroundImg: "img/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
  },
];
export const popularMovies = [
  {
    backgroundImg: "img/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "8.0",
  },
  {
    backgroundImg: "img/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "8.5",
  },
  {
    backgroundImg: "img/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.7",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.3",
  },
  {
    backgroundImg: "img/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "9.5",
  },
  {
    backgroundImg: "img/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "8.0",
  },
  {
    backgroundImg: "img/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "9.8",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "7.5",
  },
];

export const moreMovies = [
  {
    backgroundImg: "img/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "6.3",
  },
  {
    backgroundImg: "img/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "7.3",
  },
  {
    backgroundImg: "img/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.3",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.0",
  },
  {
    backgroundImg: "img/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "8.7",
  },
  {
    backgroundImg: "img/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "9.8",
  },
  {
    backgroundImg: "img/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "5.8",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "8.2",
  },
];

export const series = [
  {
    backgroundImg: "img/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "10",
  },
  {
    backgroundImg: "img/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "4.5",
  },
  {
    backgroundImg: "img/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "7.8",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.8",
  },
  {
    backgroundImg: "img/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "7.6",
  },
  {
    backgroundImg: "img/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "7.7",
  },
  {
    backgroundImg: "img/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "9.0",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "8.7",
  },
];

export const cartoons = [
  {
    backgroundImg: "img/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "5.5",
  },
  {
    backgroundImg: "img/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "7.6",
  },
  {
    backgroundImg: "img/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.7",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.6",
  },
  {
    backgroundImg: "img/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "4.5",
  },
  {
    backgroundImg: "img/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "6",
  },
  {
    backgroundImg: "img/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "8.7",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "4.3",
  },
];

export const tv = [
  {
    backgroundImg: "img/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "5",
  },
  {
    backgroundImg: "img/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "6.7",
  },
  {
    backgroundImg: "img/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.5",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "3.4",
  },
  {
    backgroundImg: "img/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "10",
  },
  {
    backgroundImg: "img/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "8.6",
  },
  {
    backgroundImg: "img/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "6.7",
  },
  {
    backgroundImg: "img/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "6.8",
  },
];

export const movieDetail = {
  movieTitle: "You are Not My Mother (2021)",
  movieBanner: "/img/bgg.png",
  description:
    "In a North Dublin housing estate Char's mother goes missing. When she returns Char is determined to uncover the truth of her disappearance and unearth the dark secrets of her family.",
  cardBanner: "/img/md1.jpg",
  videoUrl: "https://www.w3schools.com/tags/movie.mp4",
  imdbRating: "5.8",
  metaScoreRating: "74",
  saiScoreRating: "9",
  stills: [
    "https://saicord.com/uploads/posts/2022-07/1656670492_6.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670496_1.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670501_2.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670508_3.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670512_4.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670516_5.jpg",
  ],
  movieDirector: "Kate Dolan",
  Stars: "Hazel Doupe,Carolyn Bracken,Paul Reid",
  Genres: "Drama,Horror",
  Language: "English",
  Company: "Bankside Films,Fantastic Films,Screen Island",
  Writers: "Kate Dolan",
  Tagline: "<<Every Family Has Their Secrets.>>",
  Country: "Ireland",
  Year: "2021",
  Runtime: "93 min",
};
